# see:
# https://pre-commit.com/#intro
# https://github.com/Lightning-AI/lightning/blob/master/.pre-commit-config.yaml#L70

default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        exclude: |
          (?x)(
              ^lightning_api_access/ui/build|
              ^lightning_api_access/ui/yarn.lock
          )

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
        name: Format imports
        exclude: examples

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        name: Format code
        args:
          - --line-length=120
        exclude: examples

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Check PEP8
        args:
          - "--max-line-length=120"
          - "--ignore=E402,E501,F811"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.4
    hooks:
      - id: prettier
        exclude: lightning_api_access/ui
        additional_dependencies:
          - prettier@2.7.1
          - typescript@4.4.2
          - prettier-plugin-organize-imports@3.1.0
